RideShareMVC/Models/Player.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace RideShareMVC.Models
{
    public class Player
    {
        public long Id { get; set; }
        private string _key;
        public string Key
        {
            get
            {
                if(_key == null)
                {
                    _key = Regex.Replace(Name.ToLower(), "[^a-z0-9]", "-");
                }
                return _key;
            }
            set { _key = value; }
        }

        [Display(Name="Player Name")]
        [Required]
        [DataType(DataType.Text)]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Name must be between 5 and 50 characters long")]
        public string Name { get; set; }

        [Required]
        [Range(0, 100, ErrorMessage = "Must be between 0 and 100")]
        public int Age { get; set; }

        public string Country { get; set; }

        public int Rank { get; set; }

        public DateTime Created { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(20, MinimumLength =5, ErrorMessage ="Password must be atlest 5 chars")]
        public string Password { get; set; }

        [DataType(DataType.MultilineText)]
        public string Comment { get; set; }
    }
}

RideShareMVC/Models/ViewComponents/MonthlySpecialsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RideShareMVC.Models.ViewComponent
{
    //must end with viewComponent
    //must be decorated with view component 
    //or must extend view component base class
    [ViewComponent]
    public class MonthlySpecialsViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
    {

        private readonly PlayerDataContext db;

        public MonthlySpecialsViewComponent(PlayerDataContext db)
        {
            this.db = db;
        }
        //public string Invoke()
        public IViewComponentResult Invoke()
        {
            var specials = db.MonthlySpecials.ToArray();
            //return "TODO: show monthly specials";
            return View(specials);
        }

    }
}

RideShareMVC/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RideShareMVC.Models;
using RideShare.LLBLGEN.EntityClasses;
using RideShare.LLBLGEN.TypedListClasses;
using RideShare.LLBLGEN.TypedViewClasses;


namespace RideShareMVC.Controllers
{
    //[Route("rideshare")]
    //[Route("Users")]
    public class UsersController : Controller
    {
        private RideShareContext _context;
        private readonly PlayerDataContext _PlayerDb;
        public UsersController(RideShareContext context, PlayerDataContext playerDb)
        {
            _context = context;
            _PlayerDb = playerDb;
        }

        //[Route("..")]
        public IActionResult Index()
        {
            RideShare.LLBLGEN.EntityClasses.TblUser tblUser = new RideShare.LLBLGEN.EntityClasses.TblUser();
            
            return View(_context.TblUser.ToList());
        }

        public IActionResult Details(Guid? id)
        {
            dynamic myModel = new ExpandoObject();
            myModel.User = _context.Tbladdress.FirstOrDefault(m => m.UserGuid == id);
            myModel.Address = _context.TblUser.FirstOrDefault(m => m.UserGuid == id);
           
            
            //Data _dummyData = new Data();
            //ViewModelDemo vmDemo = new ViewModelDemo();
            //vmDemo.allCourses = _dummyData.GetAllCourse();
            //vmDemo.allDepartments = _dummyData.GetAllDepartment();
            //vmDemo.allEmployees = _dummyData.GetAllEmployee();
            //return View(vmDemo);

            return View(myModel);
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}

        //Actionresult type content demo
        public IActionResult Index1()
        {
            return View();
            //return new ContentResult { Content = "RideShare users" };
        }

        //using default value
        public IActionResult Index2(int id = -1)
        //int? is Nullable value that can be passed into the function
        //public IActionResult Index2(int? id)
        //public IActionResult Index2(string id)
        {
            return View();

            //if(id == null)
            //{
            //    return new ContentResult { Content = "null" };
            //}
            //else
            //{
                //return new ContentResult { Content = id.ToString() };
            //}
            //return new ContentResult { Content = id };
        }


        public IActionResult Index3()
        {
            return View();
        }

        public IActionResult Player()
        {
            var player = new Player
            {
                Name = "Nikesh",
                Age = 30,
                Country = "USA"
            };
            return View(player);
        }

        [HttpGet, Route("Users/CreatePlayer")]
        public IActionResult CreatePlayer()
        {

            return View();
        }


        [HttpPost, Route("users/CreatePlayer")]
        public IActionResult CreatePlayer([Bind("Name","Age","Country","Comment")] Player player)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            //player.Name =
            player.Rank = 1;
            player.Created = DateTime.Now;

            _PlayerDb.Players.Add(player);
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult CreateRider()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult CreateRider(Player rider)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            rider.Country = "Nepal";
            rider.Rank = 1;
            rider.Created = DateTime.Now;

            _PlayerDb.Players.Add(rider);
            _PlayerDb.SaveChanges();

            //return View();
            return RedirectToAction(
                "Rider", "Users", new
                {
                    year = rider.Created.Year,
                    month = rider.Created.Month,
                    key = rider.Key
                });
        }

        public IActionResult DisplayRiders(int page = 0) 
        {
            var pageSize = 2;
            var totalPosts = _PlayerDb.Players.Count();
            var totalPages = totalPosts / pageSize;
            var previousPage = page - 1;
            var nextPage = page + 1;

            ViewBag.PreviousPage = previousPage;
            ViewBag.HasPreviousPage = previousPage >= 0;
            ViewBag.NextPage = nextPage;
            ViewBag.HasNextPage = nextPage < totalPages;
            
            var players = _PlayerDb.Players
                .OrderByDescending(x => x.Created)
                .Skip(pageSize*page)
                .Take(pageSize)
                .ToArray();

            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView(players);

            return View(players);
        }

        [Route("{year:min(2000)}/{month:range(1,12)}/{key}")]
        public IActionResult Rider(int year, int month, string key)
        {
            var player = _PlayerDb.Players.FirstOrDefault(x => x.Key == key);
            return View(player);
        }


        //[Route("{year:min(2000)}/{month:range(1,12)}/{key}")]
        //[Route("rideshare/{year:int}/{month:int}/{key}")]
        //public IActionResult Index3(int year, int month, string key)
        //{
        //return View();
        //return new ContentResult { Content = string.Format(
        //    "year: {0}; Month: {1}; Key: {2}", year, month, key)};
        //}
        
    }
}

RideShareMVC/Views/Users/CreatePlayer.cshtml
@model RideShareMVC.Models.Player
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreatePlayer</title>
</head>
<body>
    <fieldset>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary()

            <p>
                @Html.LabelFor(x => x.Name)
                @Html.EditorFor(x => x.Name)
                @Html.ValidationMessageFor(x => x.Name)
            </p>

            <p>
                @Html.LabelFor(x => x.Age)
                @Html.TextBoxFor(x => x.Age)
                @Html.ValidationMessageFor(x => x.Age)
            </p>

            <p>
                @Html.LabelFor(x => x.Password)
                @Html.EditorFor(x => x.Password)
                @Html.ValidationMessageFor(x => x.Password)
            </p>

            <p>
                @Html.LabelFor(x => x.Comment)
                @Html.EditorFor(x => x.Comment)
                @Html.ValidationMessageFor(x => x.Comment)
            </p>
            <P>
                <button type="submit">Create Player</button>
            </P>
        }
    </fieldset>
</body>
</html>

RideShareMVC/Views/Users/CreateRider.cshtml
@*@addTagHelper "Microsoft.AspNetCore.Mvc.FormTagHelper, Microsoft.AspNetCore.Mvc.TagHelpers"*@
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@model RideShareMVC.Models.Player
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateRider</title>
</head>
<body>
    <fieldset>
        <form asp-action="CreateRider" asp-controller="Users">
            <div asp-validation-summary="All" class="input-validation-error"></div>

            <p>
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Player given name" />
                <span asp-validation-for="Name"></span>
            </p>

            <p>
                <label asp-for="Age"></label>
                <input asp-for="Age" class="form-control" placeholder="Players current age" />
                <span asp-validation-for="Age"></span>
            </p>

            <p>
                @Html.LabelFor(x => x.Password)
                @Html.EditorFor(x => x.Password)
                @Html.ValidationMessageFor(x => x.Password)
            </p>

            <p>
                <label asp-for="Comment"></label>
                <textarea asp-for="Comment" class="form-control" placeholder="Enter your comment"></textarea>
                <span asp-validation-for="Comment"></span>
            </p>

            <P>
                <button type="submit">Create Player</button>
            </P>
        </form>
</body>
</html>

RideShareMVC/Views/Users/Details.cshtml
@*@model RideShareMVC.Models.TblUser*@
@model dynamic

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

@{
    TblUser user = Model.User;
    Tbladdress address = Model.Address;
}

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => user.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => user.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => user.EmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => user.EmailAddress)
        </dd>
    </dl>
</div>
@*<div>
        <h4>User</h4>
        <hr/>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.User.Username)
            </dt>
            <dd>
                @Html.DisplayFor(model =>model.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.EmailAddress)
            </dd>
        </dl>
    </div>*@

RideShareMVC/Views/Users/DisplayRiders.cshtml
@model IEnumerable<RideShareMVC.Models.Player>
@addTagHelper *, RideShareMVC

@section header{ 
    <h1>
        This is display riders heading
    </h1>
}
<p>Below are the riders</p>

<p class="pager">
    @if (ViewBag.HasPreviousPage)
    {
        <a class="prev" href="@Url.Action("DisplayRiders","Users", new {page = ViewBag.PreviousPage})">
            &lt; Previous
        </a>
    }

    @if (ViewBag.HasNextPage)
    {
        <a class="next" href="@Url.Action("DisplayRiders","Users", new {page = ViewBag.NextPage})">
            Next &gt;
        </a>
    }
</p>

<div>
    @foreach(var Player in Model){ 
        @await Html.PartialAsync("_Rider", Player)
    }
</div>

<hr />

<div>
    <vc:monthly-specials/>
</div>

RideShareMVC/Views/Users/Index.cshtml
@model IEnumerable<RideShareMVC.Models.TblUser>

@{
    ViewBag.Title = "Users";
}

<h2>Users</h2>

<table class="table">
    <tr>
        <th>Username</th>
        <th>email Address</th>
        <th></th>
    </tr>

    @foreach (var User in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => User.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => User.EmailAddress)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@User.UserGuid">Detail</a>
            </td>
        </tr>
    }
</table>

RideShareMVC/Views/Users/Index2.cshtml
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index2</title>
</head>
<body>
    
    <p>I am on index 2 page</p>
    <p><a href="@Url.Action("Index3", "Users")" title="Index 3">Index 3 Page</a></p>
</body>
</html>

RideShareMVC/Views/Users/Index3.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
@section header{ 
    <h1>Index 3 Header Section</h1>
}
<p>Use this area to provide additional information.</p>
<p>Copyright Nikesh Maharjan @DateTime.Now.Year</p>
<li>
    <ul>
        <li><a href="@Url.Action("Index","Users")" title="Index Page">GO to users page</a></li>
        @*<li>@Html.ActionLink("Index Page", "Index","Users", null, new { title = "Users Index Page" })</li>*@
    </ul>
</li>

RideShareMVC/Views/Users/Player.cshtml
@model RideShareMVC.Models.Player
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Player</title>
</head>
<body>
    <h1>@Model.Name</h1>
    <p>
        Age = @Model.Age<br/>
        Country = @Model.Country<br/>
    </p>
</body>
</html>

RideShareMVC/Views/Users/Rider.cshtml
@model RideShareMVC.Models.Player
@{
    Layout = "_Layout";
}

@await Html.PartialAsync("_Rider")